# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: php:7.0

# Select what we should cache between builds
cache:
  paths:
  - $HOME/.composer/cache

before_script:
- apt-get update -yqq
- apt-get install -yqq git libmcrypt-dev libpq-dev libcurl4-gnutls-dev libicu-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev
# Install PHP extensions
- docker-php-ext-install mbstring mcrypt pdo_pgsql curl json intl gd xml zip bz2 opcache
# Install and run Composer
- curl -sS https://getcomposer.org/installer | php
- php composer.phar install --ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress

stages:
- build

build_phar:
  stage: build
  script:
  - php -d phar.readonly=0 bin/build
